almacen_libros/almacen_libros/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('libros/', include('libros.urls')),
    path('', TemplateView.as_view(template_name="bienvenida.html"), name='bienvenida'),
    path('', include('usuarios.urls') ),
    path('ccts/', include('ccts.urls')),

]

almacen_libros/ccts/urls.py
from django.urls import path
from ccts import views


app_name = 'ccts'

urlpatterns = [
    path('nuevo', views.CrearCentroTrabajoView.as_view(), name='nuevo' ),
    path('', views.ListaCentroTrabajoView.as_view(), name='lista' ),
    path('<int:pk>', views.DetalleCentroTrabajoView.as_view(), name='detalle' ),
]

almacen_libros/ccts/models.py
from django.db import models



class CentroTrabajo(models.Model):
    nombre = models.CharField(max_length=100)
    cct = models.CharField(max_length=100)
    latitud = models.CharField(max_length=50)
    longitud = models.CharField(max_length=50)

almacen_libros/ccts/forms.py
from django import forms
from ccts.models import CentroTrabajo

class FormCentroTrabajo(forms.ModelForm):

    class Meta:
        model = CentroTrabajo
        fields = '__all__'

        widgets = {
            # 'latitud': forms.HiddenInput(),
            # 'longitud': forms.HiddenInput(),
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
            'cct': forms.TextInput(attrs={'class':'form-control'}),
            'latitud': forms.TextInput(attrs={'readonly':'true', 'class':'form-control'}),
            'longitud': forms.TextInput(attrs={'readonly':'true', 'class':'form-control'}),

        }

almacen_libros/ccts/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView
from django.views.generic import ListView, DetailView
from ccts.forms import FormCentroTrabajo
from ccts.models import CentroTrabajo
from django.urls import reverse_lazy


class CrearCentroTrabajoView(CreateView):
    model = CentroTrabajo
    form_class = FormCentroTrabajo
    # success_url = reverse_lazy('ccts:detalle', pk=)

    def get_success_url(self):
        return reverse_lazy('ccts:detalle',args=(self.object.id,))


class ListaCentroTrabajoView(ListView):
    model = CentroTrabajo


class DetalleCentroTrabajoView(DetailView):
    model = CentroTrabajo

almacen_libros/ccts/templates/ccts/centrotrabajo_detail.html
{% extends 'base.html' %}
{% block headers %}
  <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
  <style>
    #map {
      height: 400px;
    }

    html,
    body {
      height: 100%;
      
    }
  </style>
{% endblock headers  %}

{% block contenido %}
<div class="row">
  <div class="col-sm-6 col-lg-4">
    <p>Nombre: <b>{{object.nombre}}</b></p>
    <p>CCT: <b>{{object.cct}}</b></p>
    <p>Latitud: <b>{{object.latitud}}</b></p>
    <p>Longitud: <b>{{object.longitud}}</b></p>

  </div>
  <div class="col-sm-6 col-lg-8">
    <div id="map"></div>
  </div>
</div>
{% endblock contenido %}

{% block scripts %}
<script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAyZkxzpaZ4n_W0tJKcXYb5dOFXCBYVlqs&callback=initMap&v=weekly"
      async
    ></script>
<script>
    
    let marker;

    function initMap() {
    const map = new google.maps.Map(document.getElementById("map"), {
        zoom: 11,
        center: { lat: 22.767050981989335, lng: -102.5697492675781 },
    });

    marker = new google.maps.Marker({
        map,
        draggable: true,
        animation: google.maps.Animation.DROP,
        position: { lat: {{object.latitud}}, lng: {{object.longitud}} },
    });
    }

</script>
{% endblock scripts %}

almacen_libros/ccts/templates/ccts/centrotrabajo_form.html
{% extends 'base.html' %}
{% block headers %}
  <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
  <style>
    #map {
      height: 400px;
    }

    html,
    body {
      height: 100%;
      
    }
  </style>
{% endblock headers  %}

{% block contenido %}
<div class="row">
  <div class="col-sm-6 col-lg-4">
    <form method="post" class="form">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" class="btn btn-primary" value="Guardar">
    </form>

  </div>
  <div class="col-sm-6 col-lg-8">
    <div id="map"></div>
  </div>
</div>
{% endblock contenido %}

{% block scripts %}
<script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAyZkxzpaZ4n_W0tJKcXYb5dOFXCBYVlqs&callback=initMap&v=weekly"
      async
    ></script>
<script>
    
    let marker;

    function initMap() {
    const map = new google.maps.Map(document.getElementById("map"), {
        zoom: 11,
        center: { lat: 22.767050981989335, lng: -102.5697492675781 },
    });

    marker = new google.maps.Marker({
        map,
        draggable: true,
        animation: google.maps.Animation.DROP,
        position: { lat: 22.767050981989335, lng: -102.5697492675781 },
    });
    marker.addListener("dragend", toggleBounce);
    }

    function toggleBounce() {
      console.log(marker.position);
      marker.setAnimation(google.maps.Animation.BOUNCE);
      $('#id_latitud').val(marker.position.lat);
      $('#id_longitud').val(marker.position.lng);
    }
</script>
{% endblock scripts %}

almacen_libros/ccts/templates/ccts/centrotrabajo_list.html
{% extends 'base.html' %}
{% block titulo_ventana %}
Lista de Centros de trabajo
{% endblock titulo_ventana %}

{% block contenido %}
    <h1>Lista de Centros de trabajo</h1>
    
    {% if messages %}
        {% for message in messages %}
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            danger
            {% else %}

            success
            {% endif %}
            {{ message }}
        {% endfor %}



    {% endif %}
        
    <table class="table">
        <thead>
            <tr>
                <th>CCT</th>
                <th>Nombre</th>
                <th>Latitud</th>
                <th>Logitud</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>
            {% for cct in object_list %}
                <tr>
                    <td>{{cct.cct}}</td>
                    <td>{{cct.nombre}}</td>
                    <td>{{cct.latitud}}</td>
                    <td>{{cct.longitud}}</td>
                    <td>
                        <a href="">Editar</a>
                        <a href="">Eliminar</a>
                        <a href="{% url 'ccts:detalle' cct.pk %}">Eliminar</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock contenido %}